### ISSUE TITLE
Is the traffic to AWS compressed?

### ISSUE THREAD

**Issue by elad-ep** [aws/aws-iot-device-sdk-cpp-v2#116]
Hi, I have a general question - is the traffic to AWS IoT compressed in any way? I'm using the sdk and considering compressing the data that I'm sending to IoT topics. is there a point to do so? or is the data compressed in the sdk or http/network layer?

**Comment by bretambrose** [comment]
The mqtt protocol itself is designed to be very low footprint in terms of bytes sent/received, but the payloads of messages themselves are not modified in transit in any way.  If your payloads are amenable to compression then it may be worth doing a with/without comparison and seeing if there's significant gains within your particular application.

From a design standpoint, I think we would prefer payload transformation to be something the user does before/after, rather than adding additional controls and complexity in the client itself.
