### ISSUE TITLE
AWS-Cognito - Is there a way to use it with the SDK?

### ISSUE THREAD

**Issue by HpLightcorner** [aws/aws-iot-device-sdk-cpp-v2#142]
Confirm by changing [ ] to [x] below:
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-iot-device-sdk-cpp-v2/issues/) and didn't find any solution

**Known Issue**
- [x] I'm using ATS data type endpoint: the endpoint should look like `<prefix>-ats.iot.<region>.amazonaws.com`

**Platform/OS/Device**
- x86/x64,Windows/PC

**Describe the question**
I am currently developing an application which is heavily bounded to C++. Hence, I ended up working with AWS-IOT-DEVICE-SDK-CPP-V2 as the AWS-CPP-SDK - as far as I understood - is more for managing the IOT-Service while connecting to MQTT-Topics etc. can be done with "workarounds" like `AppSync` (which does not have a C++ SDK either). I would like to connect to the MQTT-Broker directly without any further setup in AWS necessary - so finally I decided to use  AWS-IOT-DEVICE-SDK-CPP-V2 - for my Desktop-Orientated application. However, the App is going to be distributet among many clients and hence I thought - let's stick with the suggestions - and use AWS-Cognito for credential-management (in the docs it states: certificates are for devices and IAM-Roles for many customers may also be not the best option). I managed to get credentials with the `aws-cpp-sdk[cognito-idp]` - allowing me to receive:
- Token Type
- Access Token
- Expires in
- ID Token
- Refresh Token

That is what i actually tried (I know the credentials are not static, but for a test):

```
    Aws::Crt::Auth::CredentialsProviderStaticConfig defaultConfig;

    LogIn();
    std::shared_ptr<Aws::Crt::Auth::ICredentialsProvider> provider = nullptr;

    defaultConfig.AccessKeyId = Aws::Crt::ByteCursorFromCString(std_IDToken.c_str());
    defaultConfig.SecretAccessKey = Aws::Crt::ByteCursorFromCString(std_AccessToken.c_str());
    defaultConfig.SessionToken = ByteCursor();

    provider = Aws::Crt::Auth::CredentialsProvider::CreateCredentialsProviderStatic(defaultConfig);

    Aws::Iot::MqttClientConnectionConfigBuilder builder;
    Aws::Iot::WebsocketConfig config(signingRegion, provider);
    builder = Aws::Iot::MqttClientConnectionConfigBuilder(config);
```
But I end  up with ErrorCode `2056 aws-c-http: AWS_ERROR_HTTP_WEBSOCKET_UPGRADE_FAILURE`

But now I am somehow stuck. I made an IAM-Role which should give the correct access rights. 
So, maybe you can give me some guidance (or a link to an example/docs....) What are my next steps? 

- Do I have to implement my own `ICredentialsProvider` to forward Cognito-Tokens?
- How do I attach the policy to allow MQTT Subscriptions?

I found out that mixing AWS-CPP-SDK and AWS-IOT-DEVICE-SDK-CPP-V2 may be hard (due to the c-common-runtime i guess).

**Comment by bretambrose** [comment]
You're on the right track but may be missing a step.  In particular, how exactly are you sourcing those credentials?  An empty session token seems fishy to me and I'm wondering if you're missing the federation step where a cognito identity is turned into session credentials (we support this federation in the C layer, https://github.com/awslabs/aws-c-auth/blob/master/include/aws/auth/credentials.h#L294 but haven't exposed it up in the CRTs yet).  I've been intending to add a cognito credentials provider in some spare time, but other priorities have gotten in the way.

For your case, I'd work through things step-by-step starting from a sample to help isolate any problem along the way:
1. Successfully run the pubsub sample with a websocket connection and non-session profile-based credentials where the associated IAM policy is wide open (*)
1. Switch over to credentials obtained via assume role (easiest to use profile credentials provider here still)
1. Switch to cognito credentials (via AWS API calls) from a pool that maps to the previously successful role
1. Scope down the IAM policy to the connect/subscribe/publish profile you want to support.

The default credentials provider chain is enough to support the first two steps here. 

Enabling TRACE-level logging (https://github.com/awslabs/aws-crt-cpp/blob/master/include/aws/crt/Api.h#L47) should help the debugging process (you can attach their output here if you get stuck).

For your specific questions:
* Yes, you'll need to implement your own credentials provider wrapper for cognito until we implement one.
* IoT policy examples can be seen here: https://docs.aws.amazon.com/iot/latest/developerguide/connect-policy.html and since you're using IAM/websockets you can attach/edit them as you normally would and are used to (if you were using x509 certificate mtls, you would have to use the IoT console to manage permissions policy).

**Comment by HpLightcorner** [comment]
Thanks in advance for your your guidance @bretambrose, I will work through your suggestions in the next couple days and come back here with my proceedings. I suppose your are completely right - I am missing a step here. 

If I get it to work (which I suppose will hopefully not be so hard anymore - I think it is more about understanding the fundamentals how provisioning and credentials are working) - I will share my experience here with other developers - leaving the issue open in the meanwhile. And if my solution is indeed a good one, I will try to open a pull request for the cognito credentials provider.

**Comment by bretambrose** [comment]
Just a word of caution so you don't unnecessarily waste time on a PR that won't match our needs: our credentials provider implementations are all done in C (https://github.com/awslabs/aws-c-auth/tree/master/source) so that we can bind them out to all supported language CRTs.  Of course you're free to do whatever you want with your implementation, but any provider PR would need to match what currently exists in aws-c-auth.

**Comment by HpLightcorner** [comment]
Hey,
Just wanted to give some updates: I managed to connect, publish and subscribe using the cognito workflow! To be honest, the process is not that easy (at least for me). I now perform the following steps:
- Login the user using basic username/password to Cognito
- Now having the Id-Token, I perform a `getId`
- With this `IdentityId`, I can finally perform `GetCredentialsForIdentityRequest`

Which gives me an `AccessKey`, `SecretKey `and `SessionToken` connected to an IAM allowed to perform IOT-Requests.
Then I finally connect the `IdentityId` to an AWS-IOT-Policy allowing to interact with IoT-Core (A step that took me some while to understand...). 

I am using `aws-sdk-cpp[cognito-idp]`, `aws-sdk-cpp[cognito-identity]` and `aws-sdk-cpp[iot]` from the CPP-SDK. To be honest, @bretambrose - I for sure will not have the time to integrate a fully compliant credentials provider - this is completely out of scope for me (I underestimated the effort a little bit...). The `CreateCredentialsProviderStatic` does the thing for me in a first prototyp. As I have to focus on other parts of my application, what would be the easiest way to ensure valid access even when the credentials expire:
- Disconnect all Mqtt-Connections, redo authentication and setup everything from scratch?
-  How often are the credentials resolved by the IoT-SDK? Can I ensure valid credentials within a custom Credentials-Provider usind CPP-SDK and IOT-SDK? (see `onCredentialsResolved`)

If possible, I will stick with my workflow using AWS-CPP and AWS-IOT-SDK until there is an official implementation available. I am quite sure that this will not cause any troubles? 

Maybe you can give me some further advice for how to make my application convinient for administrators and users. There is (AWS-customer-related) information necessary to perform the Cognito-Authentication process, and of course I would like to keep my application as generic as possible:
- signing region
- The identity Pool-ID (Cognito)
- The IOT Policy Name (IoT-Core)
- The App Client ID (Cognito)

For me, the most obvious option is to load these parameters from a config-file or from command line parameters. The Administrator has to provide this file for all users wanting to use my application. Do you see a better option?

**Comment by bretambrose** [comment]
Great to hear about your progress; I may end up referring to some of this when building the cognito provider.

Credentials will be used by the SDK every time a new websocket connection is established which is highly variable based on network conditions.  The credentials you have fetched are only good for a certain amount of time and a provider implementation would handle everything for you, including the refresh on expiration.  Redoing everything from scratch is really awkward and you'd need to track the credentials expiration time yourself but it's the only option at the moment.  Alternatively you can proceed with what you have now and swap to our implementation when it is exposed in hopefully the not-so-distant future.

As for configuration, credentials aren't the only thing that the AWS SDKs may expose provider chains for; I know at least several include region provider chains (ours do not though).  That's a pattern you might pursue; you could pull from the aws profile file (~/.aws/credentials or ~/.aws/config), an arbitrary file, the environment, or even a local or remote service, but of course you'll have to do all the work yourself.

**Comment by HpLightcorner** [comment]
Thanks for your advices, @bretambrose 

Before i spend hours walking through the source code, do you have in mind what is going to happen when the credentials are becoming invalid? 

I am hoping for the following scenario:
The websocket connection does not receive data anymore, requests get rejected as credentials are invalid, the websocket gets disconnected somehow gracefully and then tries to automatically reconnect? If so, this would be an easy "entry point" for me to insert new credentials, I would just implement a similar provider like the static one - but in addition track time on my own (which is for sure not that hard) and query a fresh set of credentials asynchronous to the rest of the program. So when the websocket is reestablished, fresh credentials are already available.

**Comment by bretambrose** [comment]
Nothing explicitly happens when credentials go stale: IoT core will not disconnect you.  But the next time you go to reconnect, the connection attempt will fail with the websocket handshake request getting a 403 response.  

Additionally, IoT Core will drop any connection older than 24 hours, so even if you end up with a really really stable connection, eventually it will drop and the reconnect attempts will start.

Now you should know the duration of your credentials (it's probably a part of the final fetch step with Cognito or its a fixed property that documentation should tell you), so you could always just tear down and rebuild when your current set is about to expire.
