### ISSUE TITLE
run shadow sample on arm i got "error: AWS_ERROR_SUCCESS,success"

### ISSUE THREAD

**Issue by EExuke** [aws/aws-iot-device-sdk-cpp-v2#150]
./shadow-sync --endpoint "XXXXXXXXXXXXXXXXXXX" \
--cert "./certs/cert.pem" \                                                 
--key "./certs/private.pem" \                                             
--ca_file "./certs/rootCA.crt" \                                            
--thing_name "XXX" \                                                     
--shadow_property "XXX"

and it result is:
"Client Configuration initialization failed with error aws-c-common: AWS_ERROR_SUCCESS, Success."

and then, exit.

I compile it on x86 and run is ok, why I got this issue on arm after cross-compile?
please help me.

**Comment by DavidOgunsAWS** [comment]
Can you please fill out the issue template for a bugs?

Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [ ] I've searched for [previous similar issues](https://github.com/aws/aws-iot-device-sdk-cpp-v2/issues/) and didn't find any solution

**Known Issue**
- [ ] I'm using ATS data type endpoint: the endpoint should look like `<prefix>-ats.iot.<region>.amazonaws.com`
  
**Describe the bug**
A clear and concise description of what the bug is.

**Platform/OS/Device**
What are you running the sdk on?

**SDK version number**
Example: v1.5.2 

**To Reproduce (observed behavior)**
Steps to reproduce the behavior (please share code)

**Expected behavior**
A clear and concise description of what you expected to happen.

**Logs/output**
If applicable, add logs or error output.

*REMEMBER TO SANITIZE YOUR PERSONAL INFO*

```
ApiHandle::InitializeLogging(...)
```

**Additional context**
Add any other context about the problem here.

**Comment by jmklix** [comment]
Also make sure to take a look at [previous issues](https://github.com/aws/aws-iot-device-sdk-cpp-v2/issues?q=is%3Aissue++cross+compile+) to see if they can help you find a solution.
