### ISSUE TITLE
MQTT failure after internet connection resumed

### ISSUE THREAD

**Issue by jvasanthan** [aws/aws-iot-device-sdk-cpp-v2#223]
Hi Team, 

SDK - V1.10.1
Target Platform - Arm Linux 
Issue: MQTT reconnection failure

Using mobile phone hotspot for testing both scenarios
Working Scenario:
1. Run basic-pub-sub example
2. publish mqtt. mqtt success callback called. 
3. pull down internet by "ifconfig wlan0 down"
4. Verify internet connection is down
5. pull up internet by "ifconfig wlan0 up"
6. Verify internet connection is up
7. publish mqtt. mqtt success callback called. 

Non-Working Scenario:
1. Run basic-pub-sub example
2. publish mqtt. mqtt success callback called. 
3. Turn off hotspot
4. Verify internet connection is down
5. Turn on hotspot
6. Verify internet connection is up
7. publish mqtt. mqtt success callback never called.
8. publish mqtt always fails after that 

How should I debug this?

**Comment by jvasanthan** [comment]
In the Non-Working Scenario, it takes about 15 min for the sdk to detect internet connection drop. My application knows about internet connection drop and its resumption very quickly, how can I trigger sdk reconnect from my application when the internet connection drop & resume?

**Comment by jmklix** [comment]
The sdk should be reconnecting automatically, to where you should never have to trigger a reconnect yourself. Have you been able to reproduce this consistently? Does it always fail to reconnect when using a hotspot?

Also to help us with debugging can you include logs of this happening. Enable logging with `apiHandle.InitializeLogging(Aws::Crt::LogLevel::Trace, stderr);` and make sure to sanitize any personal information.

**Comment by jvasanthan** [comment]
As I mentioned in my response, the sdk is reconnecting itself after 15 minutes. I tried the below setting and it is now reconnecting after 3-3.5 minutes. is that behavior correct? 

   WithTcpKeepAlive();
   WithTcpKeepAliveTimeout(60);
   WithTcpKeepAliveInterval(30);
   WithTcpKeepAliveMaxProbes(3);
   SetReconnectTimeout(15, 30);

 Does the sdk detect internet connection only during PINGREQ and not when a mqtt publish function is called? When the internet connection is interrupted does the sdk buffer the mqtt commands sent from the application?

**Comment by graebm** [comment]
Publishing will not affect the timing for detecting connection loss.

There are 3 mechanisms for detecting connection loss:
1) If the OS socket says it's closed, the SDK immediately tries to reconnect. The timing of this is not reliable, it depends on the OS and how the connection is lost, it can take many minutes.
2) The `keepAliveTimeSecs` and `pingTimeoutMs` arguments passed to `MqttConnection::Connect()`. These control how often the SDK sends a PINGREQ, and how long the SDK will wait for a PINGRESP before assuming the connection is lost. **YOU SHOULD USE THIS TO RELIABLY DETECT CONNECTION LOSS**.
3) The various `TcpKeepAlive` controls on the `MqttClientConnectionConfigBuilder`. These control a similar mechanism at the TCP layer, rather than the MQTT layer, but is implemented in the OS and behavior may vary across platforms
