### ISSUE TITLE
fatal error: aws/crt/Api.h: No such file or directory

### ISSUE THREAD

**Issue by machadothi** [aws/aws-iot-device-sdk-cpp-v2#297]
Hi everyone!
I'm working on a IMX8M Nano microprocessor and I'm trying to add meta-aws/aws-iot-device-sdk-cpp-v2_1.10.5.bb recipe into my Yocto Project. It compiles just fine, but when I try to compile any .cpp script, I get the `fatal error: aws/crt/Api.h: No such file or directory` return.
I couldn't find any of its header files in my userspace. Am I missing anything?

I uploaded the output of a "find / -iname "*aws*" command.

[aws.log](https://github.com/aws/aws-iot-device-sdk-cpp-v2/files/6804626/aws.log)

**Comment by rpcme** [comment]
Hello @machadothi - I am the maintainer for meta-aws. A couple things to dig into here:

1/ when you are receiving the compilation error, is it when you're running the compilation on the target device, or through a recipe you've written?  The reason I ask is the recipes install the runtime libraries not the physical SDK. You can define the SDK as a DEPENDS and RDEPENDS but the header files should not be installed to the target.  The header files will be part of the Yocto SDK / eSDK target when that becomes supported.

2/ Please let me know which release branch you're using.  If those files are being installed to the target that is ... unexpected.  I will want to take a deeper look into that because it's unnecessarily impacting the target's footprint.

**Comment by machadothi** [comment]
Hi @rpcme, thanks a lot for the quick response, this clarifies a lot. 
Answering your questions:
1/ I'm trying to compile on the target device. 
2/ branch zeus

I'm not being able to compile the sample codes on the target following the README instructions in the samples folder.

```
mkdir build
cd build
cmake -DCMAKE_PREFIX_PATH="<absolute path sdk-cpp-workspace dir>" -DCMAKE_BUILD_TYPE="<Release|RelWithDebInfo|Debug>" ..
cmake --build . --config "<Release|RelWithDebInfo|Debug>"
```

I'm sending again a "find / -iname "*aws*" command output in the attachments. I'm having a hard time to figure out what "<absolute path sdk-cpp-workspace dir>" should be. As you can see in the aws.log file, there's no aws-iot-device-sdk-cpp-v2 folder in my userspace.

My image contains the aws-iot-device-sdk-cpp-v2 and aws-crt-cpp images.

Is it possible to compile in the samples in the target?

**Comment by rpcme** [comment]
Hello @machadothi another great ask which has been on the back burner for too long. I have added the issues to the meta-aws repo and linked them to this issue.  I just got back from 4 weeks leave so a bit slammed catching up but this work shouldn't take too long.

At the same time we will look at cleaning up all this installed litter you have noted.

**Comment by jmklix** [comment]
Going to close this because it looks like your problems should be fixed with the issues created on the meta-aws. Please let us know if you have any more questions.
