### ISSUE TITLE
Risk: over-authorization of AWS IoT policy

### ISSUE THREAD

**Issue by P-Verifier** [aws/aws-iot-device-sdk-cpp-v2#428]
We are a security research team and we recently discovered that there is an over-authorization security issue with this project's IoT policy.
The affected file is as following:

	1. aws-iot-device-sdk-cpp-v2/FAQ.md

**Comment by TwistedTwigleg** [comment]
Thank you for the report. The policy in question is just an example policy that is intended to help debug connection issues only during development when the client is getting disconnected. It is intended to make sure the customer's policy is not what is causing them to be disconnected as a debugging step and is not recommended for use in any real projects due to how permissive it is.

Because the policy is only for illustrative purposes for debugging and not in a live project, I am closing this issue.
