### ISSUE TITLE
Getting AWS_ERROR_MQTT_UNEXPECTED_HANGUP

### ISSUE THREAD

**Issue by TrevorChan1** [aws/aws-iot-device-sdk-cpp-v2#440]
### Describe the bug

Hello,

I'm currently trying to test out the basic_pub_sub sample, but I'm receiving the error message:

```
Connecting...
Connection failed with error libaws-c-mqtt: AWS_ERROR_MQTT_UNEXPECTED_HANGUP, The connection was closed unexpectedly.
```

The command that I'm using right now is:

```
basic-pub-sub.exe --endpoint a1klgpqe1lcq0f-ats.iot.us-east-1.amazonaws.com --root-ca C:\(path to root CA)\AmazonRootCA1.pem --cert C:\(path to cert)\cert.pem.crt --key C:\(path to key)\private.pem.key --client_id basicPubSub --topic test
```

(This command also fails if I replace root-ca with ca_file or don't include that part at all)

### Expected Behavior

The expected behavior is for the sample to connect to the MQTT server

### Current Behavior

Connection failed with error libaws-c-mqtt: AWS_ERROR_MQTT_UNEXPECTED_HANGUP, The connection was closed unexpectedly.

### Reproduction Steps

I created a build folder, went into it, did the cmake commands mentioned in the README for samples, then ran the code.

On the AWS IoT Manager page, I created a thing called "Test" that is linked to a certificate (that is active) whose downloaded certificate, key, etc. are connected to the linked filepaths in the terminal. The certificate is connected to a policy with the following JSON code: 

```json
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": [
        "iot:Publish",
        "iot:Receive"
      ],
      "Resource": [
        "arn:aws:iot:us-west-2:424091364653:topic/test/topic"
      ]
    },
    {
      "Effect": "Allow",
      "Action": [
        "iot:Subscribe"
      ],
      "Resource": [
        "arn:aws:iot:us-west-2:424091364653:topicfilter/test/topic"
      ]
    },
    {
      "Effect": "Allow",
      "Action": [
        "iot:Connect"
      ],
      "Resource": [
        "arn:aws:iot:us-west-2:424091364653:client/test-*"
      ]
    }
  ]
}
```

### Possible Solution

I've seen a lot of other people on the Issues board facing the problem, but for their paths to the keys and certificates it seems like they didn't need to put the full file path. When I do that, it gives me an error of invalid path though.

### Additional Information/Context

I'm new to using AWS IoT, so any help would be appreciated! I've mainly been testing out solutions other people have posted, but none have seemed to work so far.

### SDK version used

v2

### Environment details (OS name and version, etc.)

Windows 10

**Comment by TwistedTwigleg** [comment]
`AWS_ERROR_MQTT_UNEXPECTED_HANGUP` generally means something is missing and/or incorrect when trying to connect.

With the file paths you are passing, does it work if you put them in double quotes? So something like:

~~~
basic-pub-sub.exe --endpoint a1klgpqe1lcq0f-ats.iot.us-east-1.amazonaws.com --ca_file "C:\(path to root CA)\AmazonRootCA1.pem" --cert "C:\(path to cert)\cert.pem.crt" --key "C:\(path to key)\private.pem.key" --client_id basicPubSub --topic test
~~~

I think that will fix filepath related issues and should allow `ca_file` to work. `root-ca` was the old argument name prior to some sample reworking but passing it shouldn't do anything with the latest sample.

_________

Another thing that could be causing the disconnect is the client ID. Your policy allows clients starting with the name `test-` to connect (`test-*` part of the policy) but the client ID you are using doesn't start with this prefix. I would try and see if trying to connect with a client ID of something like `test-basicPubSub` and see if that helps.

**Comment by TrevorChan1** [comment]
Hi,

Thank you so much for your quick response! I implemented the changes so now my command looks like:

`basic-pub-sub.exe --endpoint a1klgpqe1lcq0f-ats.iot.us-east-1.amazonaws.com --ca_file "C:/(path)/AmazonRootCA1.pem" --cert "C:/(path)/cert.pem.crt" --key "C:/(path)/private.pem.key" --client_id test-basicPubSub --thing_name "Test" --topic "test/topic"`

I've also tried adding in / taking out quotation marks from some of the parts like topic and client_id, but I'm still getting the same error:
`Connection failed with error libaws-c-mqtt: AWS_ERROR_MQTT_UNEXPECTED_HANGUP, The connection was closed unexpectedly.`

Is there more I need to do with the IoT Manager? I've tried subscribing the MQTT test client to test/topic and posting onto it, but it still isn't connecting.

**Comment by TwistedTwigleg** [comment]
I think you should not need to do anything else in the IoT client - it should just need a policy, endpoint, certificate, key, and root ca file. Right off the only thing I can think of that might be causing the issue is manually specifying the client ID, but now that it has the right prefix I think it should work.

I'm going to see if I can run the sample on my Windows machine with similar arguments and see if I get the same result. 👍

**Comment by TwistedTwigleg** [comment]
Hey! Sorry about the delay - had some issues getting my Windows machine up and running.

I just compiled and ran the latest pubsub sample on my Windows 10 machine and it works fine for me. I used the following command:

~~~
 ./basic-pub-sub.exe --endpoint <endpoint> --ca_file "/d/Users/<username>/<path to ca file>/AmazonRootCA1.pem" --cert "/d/Users/<username>/<path to cert>/cert.pem.crt" --key "/d/Users/<username>/<path to key>/privatekey.pem.key.txt" --client_id test-basicPubSub --topic "test/topic"
~~~

I got the file paths by dragging and dropping the files into the terminal. The biggest difference I noticed is my path has `/d/<path>` instead of `"D://` - which may be the issue? What I would recommend doing is dragging and dropping the files into the terminal to get their paths, if you have not tried that already.

The second thing is that the policy I am using for testing is very permissive:

~~~
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": "*",
      "Resource": "*"
    }
  ]
}
~~~

Obviously this is not very secure and **not** recommended for any long term use, but it helps rule out the policy itself is causing the issue. You might want to try a permissive policy like the one I have above temporarily to see if that is what is causing the issue.
If you decide to use a permissive policy, **make sure to set it back once you are finished!**

**Comment by TrevorChan1** [comment]
It worked! I think it was an issue with the policy resources since I was using the wrong account id number. Thank you so much for your help!
