### ISSUE TITLE
details within the mqtt code 

### ISSUE THREAD

**Issue by AgeBeeTen** [aws/aws-iot-device-sdk-cpp-v2#93]
Hi,
I do not understand the line #358 in **main.cpp** of example mqtt/basic_pub_sub.
Can anybody explain why Mqtt::MqttConnection & is passed into the variable list of the lambda and never used within it ?

```
auto onPublishComplete = [payloadPtr](Mqtt::MqttConnection &, uint16_t packetId, int errorCode) {
...
```

Maybe I am not that familiar with the C++ language but anyway, I do not understand it.
Thanks
Regards

**Comment by rccarper** [comment]
It's because the Publish method (which onPublishComplete gets passed into) takes in an argument of type OnOperationCompleteHandler&&.  [OnOperationCompleteHandler is an std::function that takes an Mqtt::MqttConnection& as its first parameter.](https://github.com/awslabs/aws-crt-cpp/blob/e8f6fe4c37ffdedb243ed9968921709016fa4b60/include/aws/crt/mqtt/MqttClient.h#L92)  Even though we don't actually need it for the body of this particular callback, it's still required by the language to be in the signature so that it matches OnOperationCompleteHandler.

**Comment by AgeBeeTen** [comment]
Thanks a lot for your quick response and the explanation which helped me now to understand the things.

**Comment by rccarper** [comment]
Not a problem!  Let us know if you have any other questions.
